name: Summarize new and edited issues

on:
  issues:
    types: [opened, edited]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AI inference
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Summarize the following GitHub issue in one paragraph:
            Title: ${{ github.event.issue.title }}
            Body: ${{ github.event.issue.body }}

      - name: Debug comments fetch
        run: |
          echo "Fetching comments for issue $ISSUE_NUMBER"
          gh issue comments $ISSUE_NUMBER --json id,body || echo "Failed to fetch comments"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

      - name: Find existing AI summary comment
        id: find-comment
        run: |
          COMMENTS=$(gh issue comments $ISSUE_NUMBER --json id,body)
          COMMENT_ID=$(echo "$COMMENTS" | jq -r '.[] | select(.body | contains("[AI Summary]")) | .id' | head -n1)
          echo "Found comment ID: $COMMENT_ID"
          echo "comment_id=$COMMENT_ID" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

      - name: Post or update AI summary comment
        run: |
          set -e
          BODY="**[AI Summary]**\n\n${{ steps.inference.outputs.response }}"
          if [ -z "${{ steps.find-comment.outputs.comment_id }}" ]; then
            echo "No existing summary comment found. Posting new comment."
            if ! gh issue comment $ISSUE_NUMBER --body "$BODY"; then
              echo "Failed to post a new comment."
            fi
          else
            echo "Updating existing summary comment ID ${{ steps.find-comment.outputs.comment_id }}."
            if ! gh api repos/${{ github.repository }}/issues/comments/${{ steps.find-comment.outputs.comment_id }} \
                -X PATCH -F body="$BODY"; then
              echo "Failed to update the existing comment."
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
