name: Summarize new and edited issues

on:
  issues:
    types: [opened, edited]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AI inference
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Summarize the following GitHub issue in one paragraph:
            Title: ${{ github.event.issue.title }}
            Body: ${{ github.event.issue.body }}

      - name: Debug Outputs
        run: |
          echo "Comment ID: ${{ steps.find-comment.outputs.comment_id }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
      
      - name: Post or update AI summary comment
        run: |
          BODY="**[AI Summary]**\n\n${{ steps.inference.outputs.response }}"
          if [ -z "${{ steps.find-comment.outputs.comment_id }}" ]; then
            echo "No existing summary comment found. Posting new comment."
            gh issue comment $ISSUE_NUMBER --body "$BODY"
          else
            echo "Updating existing summary comment ID ${{ steps.find-comment.outputs.comment_id }}."
            gh api repos/${{ github.repository }}/issues/comments/${{ steps.find-comment.outputs.comment_id }} \
              -X PATCH -F body="$BODY"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
